server:
  port: 8003
spring:
  application:
    name: shop-user
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/shop?useUnicode=yes&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.shop: debug  #springboot使用loggback，默认Info级别输出日志到控制台，配置file会生成文件
  #path: /usr/log   #指定路径
  #file: springboot.log  #默认会在shop-order下面生成文件，也可以写成D://springboot.log

shop:
  security:
    clientId: test
    clientSecret: test
    expire: 14400
    refreshExpire: 1800
    signingKey: ASDFASFsdfsdfsdfsfadsf234asdfasfdas
    refreshTokenKey: refresh_jwt
    getTokenUrl: http://localhost:8003/oauth/token
    redirectUris:
      - http://localhost:8003/manager-boot/swagger-ui.html
      - http://www.baidu.com
    grantTypes:
      - password
      - authorization_code
      - refresh_token
    scopes:
      - all
      - write
      - read
    anonUri:
      - /img/**
      - /js/**
      - /css/**
    keyStorePath: mb.keystore
    keyStorePass: mbstorepass
    keyPairAlias: mbkey
    keyPairPass: mbpass
rocketmq:
  producer:
    group: producer_user_test
  name-server: 127.0.0.1:9876

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE

#设置feign客户端
ribbon:
  ReadTimeout: 5000  #feign的ribbon允许读取数据的最大时间5000毫秒
  ConnectTimeout: 5000 #允许建立连接的最大时间5000毫秒
#注册服务
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      #defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
      #defaultZone: http://localhost:7000/eureka  #注册服务的地址
       defaultZone: http://localhost:8004/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    #ip-address: ${IP_ADDRESS:127.0.0.1} #手动写上，eureka就不用解析主机名，我们给他解析好了
    instance-id: ${spring.application.name}:${server.port} #指定实例id,别名

# eureka的info页面配置，build.version以$开头结尾，必须再parent工程中配置build
info:
  app.name: ${spring.application.name}:${server.port}
  company.name: xx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$