spring:
  application:
    name: shop-gateway-80
server:
  port: 80


#注册服务
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      #defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
      #defaultZone: http://localhost:7000/eureka  #注册服务的地址
       defaultZone: http://localhost:8004/eureka/
  instance:
    #使用路由访问81的方法http://geteway-9527.com:9527/consumer-dept-feign-81/consumer/dept/get/3
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    #ip-address: ${IP_ADDRESS:127.0.0.1} #手动写上，eureka就不用解析主机名，我们给他解析好了
    #instance-id: ${spring.application.name}:${server.port} #指定实例id,别名

# eureka的info页面配置，build.version以$开头结尾，必须再parent工程中配置build
info:
  app.name: ${spring.application.name}:${server.port}
  company.name: x1x.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  #prefix: /shop 如果有这个，那么访问路径应为/shop/goods/xx
  ignored-services: "*" #*代表全部服务不能直接通过真实服务名访问，只能通过代理路径。如shop-goods只能通过/goods/**访问
  routes:
    shop-goods:
      path: /goods/**
      serviceId: shop-goods
      strip-prefix: true #true时转发去掉前缀(上面得path),不用配置
      sensitiveHeaders: #为空可以传递cookie。zuul默认拦截cookie。有值如uid，则只放行uid得cookie
      ignoredHeads: #过滤xxx得头信息。默认为空，不过滤任何头信息
    shop-order:
          path: /order/**
          serviceId: shop-order
          strip-prefix: true #true时转发去掉前缀(上面得path),不用配置
          sensitiveHeaders: #为空可以传递cookie。zuul默认拦截cookie。有值如uid，则只放行uid得cookie
          ignoredHeads: #过滤xxx得头信息。默认为空，不过滤任何头信息
    shop-user:
          path: /user/**
          serviceId: shop-user
          strip-prefix: true #true时转发去掉前缀(上面得path),不用配置
          sensitiveHeaders: #为空可以传递cookie。zuul默认拦截cookie。有值如uid，则只放行uid得cookie
          ignoredHeads: #过滤xxx得头信息。默认为空，不过滤任何头信息
    #http://geteway-9527.com:9527/dept/consumer/dept/get/2
    #manager-provider-user-7788: /user/**  #必须要配一个才能启动
    #manager-consumer-user-9000: /p/user/** #要是zuul配置中也配了content-path,那得加上
    #abcd:   #随便写，但唯一，三行等效上面一行
      #path: /abc/**
      #serviceId: consumer-dept-feign-81
      #url: baidu.com #使用url就没有负载均衡及ribbon功能.可以配置成外网如百度。url和serviceId选其中1个
  #ignored-services: #consumer-dept-80 #排除，多个服务用逗号隔开
    #mydept.serviceId: consumer-dept-feign-81
    #mydept.path: /mydept/**



